# HOT
models.1=2
biomes.1=desert badlands eroded_badlands wooded_badlands

# WARM
models.2=5
biomes.2=savanna savanna_plateau windswept_savanna jungle sparse_jungle bamboo_jungle mangrove_swamp

# SNOWY COLD
models.3=3
biomes.3=snowy_plains snowy_taiga snowy_slopes frozen_peaks jagged_peaks grove ice_spikes snowy_beach frozen_ocean deep_frozen_ocean frozen_river

# COLD (NO SNOW)
models.4=4
biomes.4=taiga old_growth_pine_taiga old_growth_spruce_taiga windswept_forest windswept_hills windswept_gravelly_hills stony_peaks
