# Warm fox awake
skins.1=fox_warm
biomes.1=desert badlands eroded_badlands wooded_badlands savanna savanna_plateau windswept_savanna jungle sparse_jungle bamboo_jungle mangrove_swamp

# Warm fox sleeping
skins.2=fox_warm_sleep
biomes.2=desert badlands eroded_badlands wooded_badlands savanna savanna_plateau windswept_savanna jungle sparse_jungle bamboo_jungle mangrove_swamp
nbt.2=Sleeping:true

# Snow fox awake
skins.3=snow_fox
biomes.3=snowy_plains snowy_taiga snowy_slopes frozen_peaks jagged_peaks grove ice_spikes snowy_beach frozen_ocean deep_frozen_ocean frozen_river

# Snow fox sleeping
skins.4=snow_fox_sleep
biomes.4=snowy_plains snowy_taiga snowy_slopes frozen_peaks jagged_peaks grove ice_spikes snowy_beach frozen_ocean deep_frozen_ocean frozen_river
nbt.4=Sleeping:true